theme: jekyll-theme-hacker
title: [Lin1337]
description: [So mais uma pessoa nesse planeta]
show_downloads: ["true"]
github:
    zip_url: http://example.com/download.zip
    another_url: another value